apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-backend
  namespace: auth-service
  labels:
    app: auth-service-backend
    tier: backend
  annotations:
    maintainer: "SOAT - Grupo 75"
    description: "Deployment do backend da aplicação Python"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-backend
  template:
    metadata:
      labels:
        app: auth-service-backend
    spec:
      containers:
        - name: auth-service-backend
          image: ${K8S_IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          resources:
            requests:
              cpu: "300m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          envFrom:
            - secretRef:
                name: auth-service-backend-secret
          startupProbe:
            httpGet:
              path: /health
              port: 8085
            failureThreshold: 60
            timeoutSeconds: 5
            periodSeconds: 5
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: APP_NAME
              value: "Auth Service"
            - name: AWS_REGION
              value: "${AWS_REGION}"
            - name: DYNAMODB_TABLE
              value: "${DYNAMODB_TABLE}"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: auth-service-backend-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-service-backend-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auth-service-backend-secret
                  key: AWS_SESSION_TOKEN
