sonar.projectKey=philipphahmann_soat-ms-auth
sonar.organization=philipphahmann
sonar.projectName=soat-ms-auth
sonar.projectVersion=1.0

sonar.host.url=https://sonarcloud.io
sonar.login=${env.SONAR_TOKEN}

sonar.sourceEncoding=UTF-8
sonar.language=py
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
