apiVersion: v1
kind: Secret
metadata:
  name: auth-service-backend-secret
  namespace: auth-service
  labels:
    app: auth-service-backend
    tier: backend
  annotations:
    maintainer: "SOAT - Grupo 75"
    description: "Segredos para autenticação do serviço de backend"
type: Opaque
stringData:
  SECRET_KEY: ${SOAT_SECRET_KEY}
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"